
name: Auto Commit

on:
  schedule:
    - cron: '06 19 * * *'

permissions:
  contents: write

jobs:
  update-text-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update TXT File
      run: echo $(date) >> testfile4.txt

    - name: Commit Changes
      run: |
        git config --local user.email "ifeanyinneji777@gmail.com"
        git config --local user.name "Nneji123"
        git add .
        git commit -am "Auto commit at $(date)"
      
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: master
